//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecreationСenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormClient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormClient()
        {
            this.ResidenceClients = new HashSet<ResidenceClients>();
        }
    
        public int clientID { get; set; }
        public string FIOClient { get; set; }
        public string passNumber { get; set; }
        public string passSeria { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResidenceClients> ResidenceClients { get; set; }
    }
}
