//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecreationСenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResidenceClients
    {
        public int residenceID { get; set; }
        public Nullable<int> roomID { get; set; }
        public Nullable<System.DateTime> arrivalDate { get; set; }
        public Nullable<System.DateTime> departureDate { get; set; }
        public int clientID { get; set; }
        public int foodID { get; set; }
        public int serviceID { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual FormClient FormClient { get; set; }
        public virtual Rooms Rooms { get; set; }
        public virtual Services Services { get; set; }
    }
}
